"""create_vinyl_records_table

Revision ID: 7f9d5552cbec
Revises: 
Create Date: 2025-09-04 23:54:30.830906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9d5552cbec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vinyl records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist', sa.String(length=50), nullable=False),
    sa.Column('album_name', sa.String(length=100), nullable=False),
    sa.Column('producer', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vinyl records_id'), 'vinyl records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vinyl records_id'), table_name='vinyl records')
    op.drop_table('vinyl records')
    # ### end Alembic commands ###
